source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
pod 'Analytics/Flurry', '2.0.17' #:git => 'https://github.com/segmentio/analytics-ios.git'
pod 'SDCAlertView', '1.4.1'
pod 'MWPhotoBrowser', :git => 'git@bitbucket.org:PROJECT/mwphotobrowser.git'
pod 'SpinKit', '~> 1.1'
pod 'RNBlurModalView', :git => 'https://github.com/iNima/RNBlurModalView.git'
pod 'iCarousel'
pod 'MPGNotification'
pod 'SSKeychain'
pod 'UICollectionViewEmptyState'
pod 'HMSegmentedControl'
pod 'EAIntroView'
pod 'AMPopTip'
pod 'CocoaHTTPServer'
pod 'TSMessages'
pod 'EDStarRating'
